blank_issues_enabled: false
contact_links:
    - name: Kernixcord Support Server
      url: https://discord.gg/champions
      about: GitHub Issues are for development, not support! Please use our [support server](https://discord.gg/champions) unless you are a Vencord Developer.
    - name: Kernixcord Installer
      url: https://github.com/kanvekin/Privxe
      about: You can find the Kernixcord Installer here
